project_id = "xfxfblhxdlzivowodpeg"

[functions.estimate-company]
verify_jwt = false

[functions.generate-estimation]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false
